#!/bin/bash

set -e

# This script sets up the github/github codespaces repository for a github/github codespace.

RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
NC='\033[0m' # No Color

# check if we are in a github/github codespace
if [[ -n "$CODESPACES" && "$GITHUB_REPOSITORY" == "github/github" ]]; then

    # do some setup

    echo -e "${GREEN}Done!${NC}"
else
    echo -e "${ORANGE}This script is intended to be run in a github/github codespace.${NC}"
fi
